# Generated by Django 4.0.4 on 2022-11-02 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('First_title', models.CharField(blank=True, max_length=255, null=True)),
                ('First_content', tinymce.models.HTMLField()),
                ('second_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Second_content', tinymce.models.HTMLField()),
                ('department_image', models.ImageField(upload_to='departments')),
                ('third_title', models.CharField(blank=True, max_length=255, null=True)),
                ('third_content', tinymce.models.HTMLField()),
                ('Disease_symptoms_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_2', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_3', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_4', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_5', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_6', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_7', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_8', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_9', models.CharField(blank=True, max_length=255, null=True)),
                ('Disease_symptoms_10', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('fourth_title', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_content', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fiveth_title', models.CharField(blank=True, max_length=255, null=True)),
                ('fiveth_content', tinymce.models.HTMLField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentDetails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
