# Generated by Django 4.0.4 on 2022-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetail',
            name='Hospital_logo',
            field=models.ImageField(default='', upload_to='departments'),
            preserve_default=False,
        ),
    ]
