# Generated by Django 4.0.4 on 2022-11-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
    ]
