# Generated by Django 4.0.4 on 2022-11-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0002_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_on']},
        ),
    ]
