# Generated by Django 4.0.4 on 2022-10-27 15:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_header', models.CharField(max_length=255)),
                ('slider_description', tinymce.models.HTMLField()),
                ('button_one', models.CharField(max_length=50)),
                ('button_two', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
