# Generated by Django 4.0.4 on 2022-10-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_slidercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image_one', models.ImageField(upload_to='Home-page')),
                ('about_image_two', models.ImageField(upload_to='Home-page')),
                ('image_two_title', models.CharField(max_length=100)),
                ('about_image_three', models.ImageField(upload_to='Home-page')),
                ('header_description', models.CharField(max_length=100)),
                ('about_header', models.CharField(max_length=255)),
                ('header_paragraph', models.TextField(blank=True, null=True)),
                ('about_services_icon', models.CharField(max_length=100)),
                ('about_services_header', models.CharField(max_length=200)),
                ('about_services_paragraph', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
