# Generated by Django 4.0.4 on 2022-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_shortabout_about_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_description', models.CharField(blank=True, max_length=100, null=True)),
                ('department_header', models.CharField(blank=True, max_length=255, null=True)),
                ('department_image', models.ImageField(blank=True, null=True, upload_to='Home-page')),
                ('department_image_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department_image_paragraph', models.TextField(blank=True, null=True)),
                ('department_icon_image', models.ImageField(blank=True, null=True, upload_to='Home-page')),
                ('department_icon_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department_icon_paragraph', models.TextField(blank=True, null=True)),
                ('department_details_button', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
