# Generated by Django 4.0.4 on 2022-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_chooseu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDoctorTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_description', models.CharField(blank=True, max_length=100, null=True)),
                ('header_title', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
