# Generated by Django 4.0.4 on 2022-11-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='all-doctors')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('specialist', models.CharField(max_length=200, unique=True)),
                ('specialist_description', models.TextField()),
                ('Biography_content', tinymce.models.HTMLField()),
                ('Graduation_one', models.CharField(blank=True, max_length=255, null=True)),
                ('University_one', models.CharField(blank=True, max_length=150, null=True)),
                ('Graduation_two', models.CharField(blank=True, max_length=255, null=True)),
                ('University_two', models.CharField(blank=True, max_length=150, null=True)),
                ('Graduation_three', models.CharField(blank=True, max_length=255, null=True)),
                ('University_three', models.CharField(blank=True, max_length=150, null=True)),
                ('Graduation_four', models.CharField(blank=True, max_length=255, null=True)),
                ('University_four', models.CharField(blank=True, max_length=150, null=True)),
                ('Graduation_five', models.CharField(blank=True, max_length=255, null=True)),
                ('University_five', models.CharField(blank=True, max_length=150, null=True)),
                ('Employe_one', models.CharField(blank=True, max_length=255, null=True)),
                ('date_one', models.CharField(blank=True, max_length=150, null=True)),
                ('Employe_two', models.CharField(blank=True, max_length=255, null=True)),
                ('date_two', models.CharField(blank=True, max_length=150, null=True)),
                ('Employe_three', models.CharField(blank=True, max_length=255, null=True)),
                ('date_three', models.CharField(blank=True, max_length=150, null=True)),
                ('Employe_four', models.CharField(blank=True, max_length=255, null=True)),
                ('date_four', models.CharField(blank=True, max_length=150, null=True)),
                ('Employe_five', models.CharField(blank=True, max_length=255, null=True)),
                ('date_five', models.CharField(blank=True, max_length=150, null=True)),
                ('Membership_one', models.CharField(blank=True, max_length=255, null=True)),
                ('Membership_two', models.CharField(blank=True, max_length=255, null=True)),
                ('Membership_three', models.CharField(blank=True, max_length=255, null=True)),
                ('Membership_four', models.CharField(blank=True, max_length=255, null=True)),
                ('Membership_five', models.CharField(blank=True, max_length=255, null=True)),
                ('Membership_six', models.CharField(blank=True, max_length=255, null=True)),
                ('Saturday', models.CharField(blank=True, max_length=50, null=True)),
                ('Saturday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Sunday', models.CharField(blank=True, max_length=50, null=True)),
                ('Sunday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Monday', models.CharField(blank=True, max_length=50, null=True)),
                ('Monday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Tuesday', models.CharField(blank=True, max_length=50, null=True)),
                ('Tuesday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Wednesday', models.CharField(blank=True, max_length=50, null=True)),
                ('Wednesday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Thursday', models.CharField(blank=True, max_length=50, null=True)),
                ('Thursday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Friday', models.CharField(blank=True, max_length=50, null=True)),
                ('Friday_time', models.CharField(blank=True, max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
