# Generated by Django 4.0.4 on 2022-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='official_cv',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
